/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ClusterHeatmap: typeof import('./src/components/ClusterHeatmap.vue')['default']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    LogModal: typeof import('./src/components/LogModal.vue')['default']
    TaskList: typeof import('./src/components/TaskList.vue')['default']
    TaskSubmitForm: typeof import('./src/components/TaskSubmitForm.vue')['default']
    WorkerCard: typeof import('./src/components/WorkerCard.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
