import os

HEARTBEAT_INTERVAL = int(os.getenv("MASTER_HEARTBEAT_INTERVAL", "5"))
HEARTBEAT_TIMEOUT = int(os.getenv("MASTER_HEARTBEAT_TIMEOUT", "15"))
CLUSTER_BROADCAST_INTERVAL = int(os.getenv("MASTER_CLUSTER_BROADCAST_INTERVAL", "1"))
LOG_BUFFER_SIZE = int(os.getenv("MASTER_LOG_BUFFER_SIZE", "1000"))
MASTER_HOST = os.getenv("MASTER_HOST", "0.0.0.0")
MASTER_PORT = int(os.getenv("MASTER_PORT", "8000"))
